name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a text file
      run: echo "Hello, world!" > hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: hello.txt
  
  download:
    runs-on: ubunut-latest
    steps:
    - name: Download Dragon text file
      uses: actions/download-artifact@v4
      with:
         name: hello-artifact
         path: ./articfacts

    - name: Read File
      run: cat ./artifacts/hello.txt